[Link del Repositorio de Github de la Tarea 11 - Joel Quilumba](https://github.com/iamjoel01/tarea11_metodos_numericos)

‎   
‎   
‎   
‎   
‎   
‎   
‎   
‎   

‎   
‎   
‎   
‎   
‎   
‎   
‎   
‎   

# CONJUNTO DE EJERCICIOS

In [4]:
import numpy as np

def gauss_jacobi(
    A: np.array, b: np.array, x0: np.array, tol: float, max_iter: int
) -> np.array:
    # --- Validación de los argumentos de la función ---
    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)
    assert A.shape[0] == A.shape[1], "La matriz A debe ser de tamaño n-by-(n)."

    if not isinstance(b, np.ndarray):
        b = np.array(b, dtype=float)
    assert b.shape[0] == A.shape[0], "El vector b debe ser de tamaño n."

    if not isinstance(x0, np.ndarray):
        x0 = np.array(x0, dtype=float)
    assert x0.shape[0] == A.shape[0], "El vector x0 debe ser de tamaño n."

    # --- Algoritmo ---
    n = A.shape[0]
    x = x0.copy()
    for k in range(1, max_iter):
        x_new = np.zeros((n, 1))  # prealloc
        for i in range(n):
            suma = sum([A[i, j] * x[j] for j in range(n) if j != i])
            x_new[i] = (b[i] - suma) / A[i, i]

        if np.linalg.norm(x_new - x) < tol:
            return x_new

        x = x_new.copy()

    return x

## Pregunta 1
**Encuentre las primeras dos iteraciones del método de Jacobi para los siguientes sistemas lineales, por
medio de $x^(0)=0$**

![](f1.png)

In [5]:

A = [
    [3, -1, 1],
    [3, 6, 2],
    [3, 3, 7]
]

b = [1, 0, 4]

x = gauss_jacobi(A, b, [0, 0, 0], 10e-5, 100)
print(x)

[[ 0.0350863 ]
 [-0.23685698]
 [ 0.65787809]]


![](f2.jpg)

In [6]:

A = [
    [10, -1, 1],
    [-1, 10, -2],
    [0, -2, 10]
]

b = [9, 7, 6]

x = gauss_jacobi(A, b, [0, 0, 0], 10e-5, 100)
print(x)
     

[[0.9159701]
 [0.9495603]
 [0.7899054]]


![](f3.jpg)

In [8]:

A = [
    [10, 5, 0, 0],
    [5, 10, -4, 0],
    [0, -4, -8, 1],
    [0, 0, -1, 5]
]

b = [6, 25, -11, -11]

x = gauss_jacobi(A, b, [0, 0, 0, 0], 10e-5, 100)
print(x)

[[-0.78792172]
 [ 2.77583088]
 [-0.29530611]
 [-2.25906474]]


![](f4.jpg)

In [10]:

A = [
    [4, 1, 1, 0, 1],
    [-1, -3, 1, 1, 0],
    [2, 1, 5, -1, -1],
    [-1, -1, -1, 4, 0],
    [0, 2, -1, 1, 4]
]

b = [6, 6, 6, 6, 6]

x = gauss_jacobi(A, b, [0, 0, 0, 0, 0], 10e-5, 100)
print(x)

[[ 0.78661584]
 [-1.00257369]
 [ 1.86634212]
 [ 1.91259293]
 [ 1.98974776]]


## Pregunta 2
**Repita el ejercicio 1 usando el método de Gauss-Siedel**

In [11]:

def gauss_seidel(
    A: np.array, b: np.array, x0: np.array, tol: float, max_iter: int
) -> np.array:
    # --- Validación de los argumentos de la función ---
    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)
    assert A.shape[0] == A.shape[1], "La matriz A debe ser de tamaño n-by-(n)."

    if not isinstance(b, np.ndarray):
        b = np.array(b, dtype=float)
    assert b.shape[0] == A.shape[0], "El vector b debe ser de tamaño n."

    if not isinstance(x0, np.ndarray):
        x0 = np.array(x0, dtype=float)
    assert x0.shape[0] == A.shape[0], "El vector x0 debe ser de tamaño n."

    # --- Algoritmo ---
    n = A.shape[0]
    x = x0.copy()

    for k in range(1, max_iter):
        x_new = np.zeros((n, 1))  # prealloc
        for i in range(n):
            suma = sum([A[i, j] * x_new[j] for j in range(i) if j != i]) + sum(
                [A[i, j] * x[j] for j in range(i, n) if j != i]
            )
            x_new[i] = (b[i] - suma) / A[i, i]

        if np.linalg.norm(x_new - x) < tol:
            return x_new

        x = x_new.copy()

    return x

![](f1.png)

In [12]:

A = [
    [3, -1, 1],
    [3, 6, 2],
    [3, 3, 7]
]

b = [1, 0, 4]

x = gauss_seidel(A, b, [0, 0, 0], 10e-5, 100)
print(x)


[[ 0.03510326]
 [-0.23683891]
 [ 0.6578867 ]]


![](f2.jpg)

In [13]:
A = [
    [10, -1, 1],
    [-1, 10, -2],
    [0, -2, 10]
]

b = [9, 7, 6]

x = gauss_seidel(A, b, [0, 0, 0], 10e-5, 100)
print(x)

[[0.91596497]
 [0.94957898]
 [0.7899158 ]]


![](f3.jpg)

In [14]:
A = [
    [10, 5, 0, 0],
    [5, 10, -4, 0],
    [0, -4, -8, 1],
    [0, 0, -1, 5]
]

b = [6, 25, -11, -11]

x = gauss_seidel(A, b, [0, 0, 0, 0], 10e-5, 100)
print(x)

[[-0.78791707]
 [ 2.77583885]
 [-0.29530191]
 [-2.25906038]]


![](f4.jpg)

In [15]:
A = [
    [4, 1, 1, 0, 1],
    [-1, -3, 1, 1, 0],
    [2, 1, 5, -1, -1],
    [-1, -1, -1, 4, 0],
    [0, 2, -1, 1, 4]
]

b = [6, 6, 6, 6, 6]

x = gauss_seidel(A, b, [0, 0, 0, 0, 0], 10e-5, 100)
print(x)

[[ 0.78663577]
 [-1.00257108]
 [ 1.86632614]
 [ 1.91259771]
 [ 1.98971765]]


## Pregunta 3
**Utilice el método de Jacobi para resolver los sistemas lineales en el ejercicio 1, con TOL = 10-3.**

* Literal A

In [16]:
A = [
    [3, -1, 1],
    [3, 6, 2],
    [3, 3, 7]
]

b = [1, 0, 4]

x = gauss_jacobi(A, b, [0, 0, 0], 10e-3, 100)
print(x)

[[ 0.03516089]
 [-0.23570619]
 [ 0.65922185]]


* Literal B

In [17]:

A = [
    [10, -1, 1],
    [-1, 10, -2],
    [0, -2, 10]
]

b = [9, 7, 6]

x = gauss_jacobi(A, b, [0, 0, 0], 10e-3, 100)
print(x)

[[0.91603]
 [0.94913]
 [0.78962]]


* Literal C

In [18]:

A = [
    [10, 5, 0, 0],
    [5, 10, -4, 0],
    [0, -4, -8, 1],
    [0, 0, -1, 5]
]

b = [6, 25, -11, -11]

x = gauss_jacobi(A, b, [0, 0, 0, 0], 10e-3, 100)
print(x)

[[-0.788375  ]
 [ 2.77715625]
 [-0.29553125]
 [-2.26032813]]


* Literal D

In [19]:

A = [
    [4, 1, 1, 0, 1],
    [-1, -3, 1, 1, 0],
    [2, 1, 5, -1, -1],
    [-1, -1, -1, 4, 0],
    [0, 2, -1, 1, 4]
]

b = [6, 6, 6, 6, 6]

x = gauss_jacobi(A, b, [0, 0, 0, 0, 0], 10e-3, 100)
print(x)

[[ 0.78718101]
 [-1.00174151]
 [ 1.8658388 ]
 [ 1.91274157]
 [ 1.98672138]]


## Pregunta 4
**Utilice el método de Gauss-Siedel para resolver los sistemas lineales en el ejercicio 1, con TOL = 10-3.**

* Literal A

In [20]:

A = [
    [3, -1, 1],
    [3, 6, 2],
    [3, 3, 7]
]

b = [1, 0, 4]

x = gauss_seidel(A, b, [0, 0, 0], 10e-3, 100)
print(x)

[[ 0.0361492 ]
 [-0.23660752]
 [ 0.65733928]]


* Literal B

In [21]:
A = [
    [10, -1, 1],
    [-1, 10, -2],
    [0, -2, 10]
]

b = [9, 7, 6]

x = gauss_seidel(A, b, [0, 0, 0], 10e-3, 100)
print(x)


[[0.91593697]
 [0.94956218]
 [0.78991244]]


* Literal C

In [22]:

A = [
    [10, 5, 0, 0],
    [5, 10, -4, 0],
    [0, -4, -8, 1],
    [0, 0, -1, 5]
]

b = [6, 25, -11, -11]

x = gauss_seidel(A, b, [0, 0, 0, 0], 10e-3, 100)
print(x)

[[-0.78802812]
 [ 2.77579328]
 [-0.29528544]
 [-2.25905709]]


* Literal D

In [23]:

A = [
    [4, 1, 1, 0, 1],
    [-1, -3, 1, 1, 0],
    [2, 1, 5, -1, -1],
    [-1, -1, -1, 4, 0],
    [0, 2, -1, 1, 4]
]

b = [6, 6, 6, 6, 6]

x = gauss_seidel(A, b, [0, 0, 0, 0, 0], 10e-3, 100)
print(x)
     

[[ 0.78616258]
 [-1.00240703]
 [ 1.86606999]
 [ 1.91245638]
 [ 1.98960692]]


## Pregunta 5
**El sistema lineal**

![](f5.jpg)

**tiene la solución (1, 2, -1)**

a. Muestre que el método de Jacobi con $x^{(0)} = 0$ falla al proporcionar una buena aproximación
después de 25 iteraciones.

In [24]:
A = [
    [2, -1, 1],
    [2, 2, 2],
    [-1, -1, 2]
]

b = [-1, 4, -5]

x = gauss_jacobi(A, b, [0, 0, 0], 10e-5, 25)
print(x)

[[ -7.73114914]
 [-32.92459655]
 [  7.73114914]]


b. Utilice el método de Gauss-Siedel con $x^{(0)} = 0$ para aproximar la solución para el sistema lineal
dentro de $10^−5$

In [25]:
A = [
    [2, -1, 1],
    [2, 2, 2],
    [-1, -1, 2]
]

b = [-1, 4, -5]

x = gauss_seidel(A, b, [0, 0, 0], 10e-5, 25)
print(x)

[[ 0.99998474]
 [ 2.00001717]
 [-0.99999905]]


## Pregunta 6
**El sistema lineal**

![](f7.jpg)

**tiene la solución (0.9, -0.8, 0.7)**

a. ¿La matriz de coeficientes tiene diagonal estrictamente dominante?

![](f8.jpg)

Si, ya que los elementos de la diagonal en cada fila son mayores a la sumatoria de los demás
valores, en otras palabras, cumple la siguiente propiedad.

![](ff.jpg)

b. Utilice el método iterativo de Gauss-Siedel para aproximar la solución para el sistema lineal con
una tolerancia de $10_{22}$ y un máximo de $300$ iteraciones.

In [29]:

A = [
    [1, 0, -1],
    [-0.5, 1, -0.25],
    [1, -0.5, 1]
]

b = [0.2, -1.425, 2]

x = gauss_seidel(A, b, [0, 0, 0], 10e-22, 300)
print(x)
print()
y = gauss_jacobi(A, b, [0, 0, 0], 10e-22, 300)
print(y)

[[ 0.9]
 [-0.8]
 [ 0.7]]

[[ 0.89979164]
 [-0.80015806]
 [ 0.70025541]]


c.  ¿Qué pasa en la parte b) cuando el sistema cambia por el siguiente?

![](f9.jpg)

In [31]:

A = [
    [1, 0, -2],
    [-0.5, 1, -0.25],
    [1, -0.5, 1]
]

b = [0.2, -1.425, 2]

x = gauss_seidel(A, b, [0, 0, 0], 10e-22, 300)
print(x)
print()
y = gauss_jacobi(A, b, [0, 0, 0], 10e-22, 300)
print(y)
     

[[-1.56863478e+41]
 [-9.80396739e+40]
 [ 1.07843641e+41]]

[[-1.79225360e+43]
 [-4.51500391e+42]
 [ 6.72394565e+42]]


## Pregunta 8
**Un cable coaxial está formado por un conductor interno de 0.1 pulgadas cuadradas y un conductor externo
de 0.5 pulgadas cuadradas. El potencial en un punto en la sección transversal del cable se describe
mediante la ecuación de Laplace.
Suponga que el conductor interno se mantiene en 0 volts y el conductor externo se mantiene en 110 volts. Aproximar
el potencial entre los dos conductores requiere resolver el siguiente sistema lineal.**

![](fff.jpg)

a. ¿La matriz es estrictamente diagonalmente dominante?

Si ya que cumple

![](ff.jpg)

b. Resuelva el sistema lineal usando el método de Jacobi con $x^{(0)} = 0$ y TOL = $10_{-2}$.

In [32]:
A = [
   [4, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
   [-1, 4, .1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
   [0, -1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0],
   [0, 0, -1, 4, 0, -1, 0, 0, 0, 0, 0, 0],
   [-1, 0, 0, 0, 4, 0, -1, 0, 0, 0, 0, 0],
   [0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0, 0],
   [0, 0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0],
   [0, 0, 0, 0, 0, -1, 0, 4, 0, 0, 0, -1],
   [0, 0, 0, 0, 0, 0, -1, 0, 4, -1, 0, 0],
   [0, 0, 0, 0, 0, 0, 0, 0, -1, 4, -1, 0],
   [0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 4, -1],
   [0, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 4]
]

b = [220, 110, 110, 220, 110, 110, 110, 110, 220, 110, 110, 220]

x = gauss_jacobi(A, b, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 10, 250)
print(x)

[[81.59873047]
 [46.05927734]
 [59.57724609]
 [84.89550781]
 [62.87402344]
 [63.58300781]
 [63.58300781]
 [63.70117188]
 [85.72265625]
 [63.70117188]
 [63.70117188]
 [85.72265625]]


c. Repita la parte b) mediante el método de Gauss-Siedel.

In [33]:

A = [
   [4, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
   [-1, 4, .1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
   [0, -1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0],
   [0, 0, -1, 4, 0, -1, 0, 0, 0, 0, 0, 0],
   [-1, 0, 0, 0, 4, 0, -1, 0, 0, 0, 0, 0],
   [0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0, 0],
   [0, 0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0],
   [0, 0, 0, 0, 0, -1, 0, 4, 0, 0, 0, -1],
   [0, 0, 0, 0, 0, 0, -1, 0, 4, -1, 0, 0],
   [0, 0, 0, 0, 0, 0, 0, 0, -1, 4, -1, 0],
   [0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 4, -1],
   [0, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 4]
]

b = [220, 110, 110, 220, 110, 110, 110, 110, 220, 110, 110, 220]

x = gauss_seidel(A, b, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 10, 250)
print(x)

[[82.04627686]
 [46.53746918]
 [60.13291847]
 [85.94719503]
 [63.77875061]
 [65.11658196]
 [64.70993881]
 [65.5444085 ]
 [87.1606638 ]
 [65.43725257]
 [65.62457615]
 [87.68528953]]


[Link del Repositorio de Github de la Tarea 11 - Joel Quilumba](https://github.com/iamjoel01/tarea11_metodos_numericos)